# config.py

BINANCE_API_KEY = 'czQXMbDiSsFSTMxjMtkRkYEmXMhVxi31QAIbQdfhcY9sqtjzGPL8k7i8YXfHcvNX'
BINANCE_API_SECRET = '7AapQSR44cuRbxKY3IzsuG6xRePrBJCyinUswTrj6VzLkQPeK2Eiml70rzNMEGY4'

# Telegram API keys
#TELEGRAM_BOT_TOKEN = 
#TELEGRAM_CHAT_ID = 


# List of futures trading pairs (symbols)
symbols = [
    'WLDUSDT', 'SEIUSDT', 'CYBERUSDT', 'ARKUSDT','NTRNUSDT', 'TIAUSDT', 'MEMEUSDT',
    'ORDIUSDT', 'BEAMXUSDT', 'BLURUSDT', 'JTOUSDT', '1000SATSUSDT',
    '1000BONKUSDT', 'ACEUSDT', 'NFPUSDT', 'AIUSDT', 'XAIUSDT', 'MANTAUSDT', 'POWRUSDT',
    'JASMYUSDT', 'RNDRUSDT',
    'BICOUSDT', 'FXSUSDT', 'HIGHUSDT', 'CVXUSDT', 'PEOPLEUSDT', 'SPELLUSDT',
    'JOEUSDT', 'ACHUSDT', 'IMXUSDT', 'GLMRUSDT', 'API3USDT',
    'WOOUSDT', 'ASTRUSDT', 'GMTUSDT', 'APEUSDT',
    'STEEMUSDT', 'GALUSDT', 'LDOUSDT', 'BTCUSDT', 'ETHUSDT',
    'BNBUSDT', 'NEOUSDT', 'LTCUSDT', 'QTUMUSDT', 'ADAUSDT', 'XRPUSDT', 'EOSUSDT', 'IOTAUSDT', 'XLMUSDT',
    'ONTUSDT', 'TRXUSDT', 'ETCUSDT', 'ICXUSDT', 'VETUSDT',
    'LINKUSDT', 'WAVESUSDT', 'ONGUSDT', 'HOTUSDT', 'ZILUSDT', 'ZRXUSDT', 'FETUSDT', 'BATUSDT',
    'XMRUSDT', 'ZECUSDT', 'IOSTUSDT', 'CELRUSDT', 'DASHUSDT', 'OMGUSDT', 'THETAUSDT', 'ENJUSDT',
    'MATICUSDT', 'ATOMUSDT', 'ONEUSDT', 'FTMUSDT', 'ALGOUSDT', 'DOGEUSDT',
    'DUSKUSDT', 'ANKRUSDT', 'MTLUSDT', 'DENTUSDT',
    'KEYUSDT', 'STMXUSDT', 'CHZUSDT', 'BANDUSDT',
    'XTZUSDT', 'RENUSDT', 'RVNUSDT', 'HBARUSDT', 'NKNUSDT', 'STXUSDT', 'KAVAUSDT', 'ARPAUSDT', 'IOTXUSDT',
    'RLCUSDT', 'BCHUSDT', 'OGNUSDT',
    'LSKUSDT', 'BNTUSDT', 'MBLUSDT',
    'COTIUSDT', 'STPTUSDT', 'SOLUSDT', 'CTSIUSDT', 'CHRUSDT',
    'MDTUSDT', 'KNCUSDT', 'LRCUSDT', 'COMPUSDT',
    'ZENUSDT', 'SNXUSDT', 'DGBUSDT', 'SXPUSDT', 'MKRUSDT',
    'STORJUSDT', 'MANAUSDT', 'YFIUSDT', 'BALUSDT', 'BLZUSDT',
    'ANTUSDT', 'CRVUSDT', 'SANDUSDT', 'OCEANUSDT', 'NMRUSDT', 'DOTUSDT', 'LUNA2USDT', 'RSRUSDT',
    'TRBUSDT', 'SUSHIUSDT', 'KSMUSDT', 'EGLDUSDT', 'RUNEUSDT', 'UMAUSDT',
    'BELUSDT', 'UNIUSDT', 'OXTUSDT', 'AVAXUSDT', 'FLMUSDT',
    'XVSUSDT', 'ALPHAUSDT', 'AAVEUSDT', 'NEARUSDT', 'FILUSDT', 'INJUSDT', 'AUDIOUSDT', 'CTKUSDT',
    'AXSUSDT', 'STRAXUSDT', 'UNFIUSDT', 'ROSEUSDT', 'XEMUSDT', 'SKLUSDT',
    'GRTUSDT', '1INCHUSDT', 'REEFUSDT', 'CELOUSDT', 'RIFUSDT',
    'TRUUSDT', 'CKBUSDT', 'TWTUSDT', 'LITUSDT', 'SFPUSDT', 'DODOXUSDT', 'CAKEUSDT',
    'BADGERUSDT', 'ALICEUSDT', 'LINAUSDT', 'PERPUSDT', 'SUPERUSDT',
    'CFXUSDT', 'TLMUSDT',
    'BAKEUSDT', 'SLPUSDT', '1000SHIBUSDT', 'ICPUSDT', 'ARUSDT', 'MASKUSDT', 'LPTUSDT',
    'XVGUSDT', 'ATAUSDT', 'APTUSDT', 'ARBUSDT'
]

# Time interval for fetching historical data
time_interval = '15m'  # You can change this to '4h', '1d', etc.
